apiVersion: v1
kind: Secret
metadata:
  name: zitadel-actions-api-secret
  labels:
    app.kubernetes.io/name: zitadel-actions-api
    app.kubernetes.io/part-of: zitadel
type: Opaque
stringData:
  # Signing key issued by ZITADEL when creating the Action Target (optional)
  # Leave empty if you do not use HMAC signature verification
  ZITADEL_SIGNING_KEY: ""
