apiVersion: v1
kind: Service
metadata:
  name: zitadel-actions-api
  labels:
    app.kubernetes.io/name: zitadel-actions-api
    app.kubernetes.io/part-of: zitadel
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: zitadel-actions-api
